@host = http://localhost:5063

### Get all enrollments
GET {{host}}/api/enrollments

###

### Create enrollment
POST {{host}}/api/enrollments
Content-Type: application/json

{
  "studentId": "S-001",
  "courseCode": "CS-101"
}

###

### Test ProblemDetails
GET {{host}}/api/error

###

### Protected endpoint
GET {{host}}/api/assessments/results

###